name: Check

description: Check the health of a project

inputs:
  project:
    description: The project to check
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        cache: pnpm
        node-version-file: package.json

    - run: pnpm --filter="$PROJECT" install
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}

    - run: pnpm run format
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}

    - run: pnpm --filter="$PROJECT" run generate:types
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}

    - run: pnpm --filter="$PROJECT" run lint
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}
