name: Check

description: Check the health of a project

runs:
  using: composite
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        cache: pnpm
        node-version-file: package.json

    - run: pnpm install
      shell: bash

    - run: pnpm run check
      shell: bash
