name: Check

description: Check the health of a project

inputs:
  project:
    description: The project to check
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        cache: pnpm
        node-version-file: package.json

    - run: pnpm --filter="$PROJECT" install
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}

    - run: pnpm run format
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}

    - run: pnpm --filter="$PROJECT" run generate:types
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}

    - run: pnpm --filter="$PROJECT" run lint
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}
