name: Deploy

description: Deploy an app

inputs:
  app:
    description: The name of the app to deploy
    required: true
  build-artifact-name:
    description: The name of the build artifact to download
    required: true
  cloudflare-api-token:
    description: The Cloudflare API token
    required: true
  cloudflare-account-id:
    description: The Cloudflare account ID
    required: true
  cloudflare-project-name:
    description: The Cloudflare project name to deploy to
    required: true
  directory:
    description: The directory of static files to upload
    required: true
  github-token:
    description: The GITHUB_TOKEN secret
    required: true
  github-environment:
    description: The GitHub environment to deploy to
    required: true
  working-directory:
    description: The working directory to run the deployment from
    required: true

runs:
  using: composite
  steps:
    - name: Check if required variables are defined
      run: |
        echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"
        echo "CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID:?configuration variable is not defined}"
        echo "CLOUDFLARE_PROJECT_NAME: ${CLOUDFLARE_PROJECT_NAME:?configuration variable is not defined}"
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
        CLOUDFLARE_PROJECT_NAME: ${{ inputs.cloudflare-project-name }}

    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        cache: pnpm
        node-version-file: package.json

    - run: pnpm --filter="$APP" install
      shell: bash
      env:
        APP: ${{ inputs.app }}

    - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: ${{ inputs.build-artifact-name }}

    - name: Untar build artifact
      run: tar xvf "${BUILD_ARTIFACT_NAME}.tar"
      shell: bash
      env:
        BUILD_ARTIFACT_NAME: ${{ inputs.build-artifact-name }}

    - uses: unlike-ltd/github-actions-cloudflare-pages@5428201f91a158bbf876391773769e720c80dabb # v2.4.1
      with:
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}
        cloudflare-account-id: ${{ inputs.cloudflare-account-id }}
        cloudflare-project-name: ${{ inputs.cloudflare-project-name }}
        directory: ${{ inputs.directory }}
        github-token: ${{ inputs.github-token }}
        github-environment: ${{ inputs.github-environment }}
        working-directory: ${{ inputs.working-directory }}
