name: Deploy

description: Deploy the app

inputs:
  app:
    description: The app to deploy
    required: true
  build-artifact-name:
    description: The name of the build artifact to deploy
    required: true
  public-path:
    description: The path to the public directory
    required: true
  environment:
    description: The environment to deploy to
    required: true

runs:
  using: composite
  steps:
    - name: Check if required variables are defined
      run: |
        echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"
        echo "CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID:?configuration variable is not defined}"
        echo "CLOUDFLARE_PROJECT_NAME: ${CLOUDFLARE_PROJECT_NAME:?configuration variable is not defined}"
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}

    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version-file: package.json

    - run: pnpm install --filter="$APP"
      shell: bash
      env:
        APP: ${{ inputs.app }}

    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact-name }}

    - name: Untar build artifact
      run: tar xvf "$BUILD_ARTIFACT_NAME".tar
      shell: bash
      env:
        BUILD_ARTIFACT_NAME: ${{ inputs.build-artifact-name }}

    - uses: unlike-ltd/github-actions-cloudflare-pages@8c09c46bd39321b4aa3784852491d9e4f09e1566 # v1.2.0
      with:
        cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
        directory: ${{ inputs.public-path }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-environment: ${{ inputs.environment }}
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
