name: Deploy

description: Deploy an app

inputs:
  app:
    description: The name of the app to deploy
    required: true
  build-artifact-name:
    description: The name of the build artifact to download
    required: true
  directory-path:
    description: The path to the directory of static files to upload
    required: true
  cloudflare-api-token:
    description: The Cloudflare API token
    required: true
  cloudflare-account-id:
    description: The Cloudflare account ID
    required: true
  cloudflare-project-name:
    description: The Cloudflare project name to deploy to
    required: true
  github-token:
    description: The GITHUB_TOKEN secret
    required: true
  github-environment:
    description: The GitHub environment to deploy to
    required: true

runs:
  using: composite
  steps:
    - name: Check if required variables are defined
      run: |
        echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"
        echo "CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID:?configuration variable is not defined}"
        echo "CLOUDFLARE_PROJECT_NAME: ${CLOUDFLARE_PROJECT_NAME:?configuration variable is not defined}"
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
        CLOUDFLARE_PROJECT_NAME: ${{ inputs.cloudflare-project-name }}

    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version-file: package.json

    - run: pnpm install --filter="$APP"
      shell: bash
      env:
        APP: ${{ inputs.app }}

    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact-name }}

    - name: Untar build artifact
      run: tar xvf "$BUILD_ARTIFACT_NAME".tar
      shell: bash
      env:
        BUILD_ARTIFACT_NAME: ${{ inputs.build-artifact-name }}

    - uses: unlike-ltd/github-actions-cloudflare-pages@159278d1b12c975d1d5e538720e4da343131ede3 # v1.3.0
      with:
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}
        cloudflare-account-id: ${{ inputs.cloudflare-account-id }}
        cloudflare-project-name: ${{ inputs.cloudflare-project-name }}
        directory: ${{ inputs.directory-path }}
        github-token: ${{ inputs.github-token }}
        github-environment: ${{ inputs.github-environment }}
