source:
  - apps/admin/functions/**
  - apps/admin/public/**
  - apps/admin/src/**
  - apps/admin/astro.config.ts
  - apps/admin/package.json
  - apps/admin/pnpm-lock.yaml
  - apps/admin/tsconfig.json
