name: Prepare

description: Prepare prerequisites for subsequent jobs in the workflow

inputs:
  project:
    description: The project to prepare for
    required: true

outputs:
  environment:
    description: The environment to deploy to
    value: ${{ inputs.project }} ${{ github.ref_name == github.event.repository.default_branch && '(production)' || '(preview)' }}
  needs-deploy:
    description: Whether the project needs to be deployed
    value: ${{ steps.set-needs-deploy.outputs.needs-deploy }}

runs:
  using: composite
  steps:
    - id: set-needs-deploy
      name: Set output needs-deploy
      run: |
        mapfile -t messages < <(jq '.[].message' -r <<< "$COMMITS")

        for message in "${messages[@]}"; do
          prefix="${message%%:*}"
          type="${prefix%%[(!]*}"
          scope="$(awk -F '[()]' '{print $2}' <<< "$prefix")"

          if [[ $scope == 'no-release' ]]; then
            continue
          fi

          if [[ $prefix =~ !$ || $type =~ ^(feat|fix|perf)$ ]]; then
            if [[ $scope && $scope != "$PROJECT" ]]; then
              continue
            fi

            echo 'needs-deploy=true' >> "$GITHUB_OUTPUT"

            exit 0
          fi
        done

        echo 'needs-deploy=false' >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}
        COMMITS: ${{ toJSON(github.event.commits) }}
