name: Prepare

description: Prepare prerequisites for subsequent jobs

inputs:
  project:
    description: The project to prepare for
    required: true
    type: string

outputs:
  environment:
    description: The environment to deploy to
    value: ${{ inputs.project }} ${{ github.ref_name == github.event.repository.default_branch && '(production)' || '(preview)' }}
  source-files-changed:
    description: Whether the source files have changed
    value: ${{ steps.filter.outputs.source }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: .github/filters/${{ inputs.project }}.yaml
