name: Prepare

description: Prepare prerequisites for subsequent jobs in the workflow

inputs:
  project:
    description: The project to prepare for
    required: true

outputs:
  environment:
    description: The environment to deploy to
    value: ${{ inputs.project }} ${{ github.ref_name == github.event.repository.default_branch && '(production)' || '(preview)' }}
  needs-deploy:
    description: Whether the project needs to be deployed
    value: ${{ steps.analyze-commits.outputs.needs-deploy }}

runs:
  using: composite
  steps:
    - id: analyze-commits
      uses: ./.github/actions/analyze-commits
      with:
        project: ${{ inputs.project }}
