name: Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build for ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - run: 'echo "environment: $ENVIRONMENT"'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          path: |
            dist/
            stats.html
          if-no-files-found: error
