name: Build

on:
  workflow_call:
    inputs:
      node-modules-cache-path:
        required: true
        type: string
      node-modules-cache-key:
        required: true
        type: string
    outputs:
      build-artifact-cache-path:
        description: The path to the build artifact to cache
        value: ${{ jobs.build.outputs.build-artifact-cache-path }}
      build-artifact-cache-key:
        description: The cache key for the build artifact
        value: ${{ jobs.build.outputs.build-artifact-cache-key }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-artifact-cache-path: ${{ steps.set-build-artifact-cache-path.outputs.build-artifact-cache-path }}
      build-artifact-cache-key: ${{ steps.set-build-artifact-cache-key.outputs.build-artifact-cache-key }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
        timeout-minutes: 1

      - id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.node-modules-cache-path }}
          key: ${{ inputs.node-modules-cache-key }}

      - if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - id: set-build-artifact-cache-path
        name: Set build artifact name
        run: echo "build-artifact-cache-path=dist/" >> "$GITHUB_OUTPUT"

      - id: set-build-artifact-cache-key
        name: Set build artifact name
        run: echo "build-artifact-cache-key=build-artifact-run-$GITHUB_RUN_ID" >> "$GITHUB_OUTPUT"

      - uses: actions/cache/save@v4
        with:
          path: ${{ steps.set-build-artifact-cache-path.outputs.build-artifact-cache-path }}
          key: ${{ steps.set-build-artifact-cache-key.outputs.build-artifact-cache-key }}

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: stats-artifact-run-${{ github.run_id }}
          path: stats.html
          if-no-files-found: error
    timeout-minutes: 5
