name: Build

on:
  workflow_call:
    inputs:
      pnpm-store-cache-path:
        required: true
        type: string
      pnpm-store-cache-key:
        required: true
        type: string
    outputs:
      build-artifact-name:
        description: The name of the build artifact
        value: ${{ jobs.build.outputs.build-artifact-name }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-artifact-name: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}
    steps:
      - uses: actions/checkout@v4

      - run: pnpm install

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
        timeout-minutes: 1

      - run: pnpm run build

      - id: set-build-artifact-name
        name: Set build artifact name
        run: echo "build-artifact-name=build-artifact-run-$GITHUB_RUN_ID" >> "$GITHUB_OUTPUT"

      - name: Tar build artifact
        run: tar cvf "$BUILD_ARTIFACT_NAME".tar dist/
        env:
          BUILD_ARTIFACT_NAME: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}
          path: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}.tar
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: stats-artifact-run-${{ github.run_id }}
          path: stats.html
          if-no-files-found: error
    timeout-minutes: 5
