name: Build

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine-environment.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        timeout-minutes: 0.25
        with:
          cache: npm
          node-version-file: package.json
      - id: determine-environment
        run: echo "environment=${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}" >> "$GITHUB_OUTPUT"
      - run: npm ci
      - uses: actions/cache/save@v4
        with:
          path: node_modules
          key: node-dependencies-${{ github.run_number }}-${{ github.run_attempt }}
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ steps.determine-environment.outputs.environment }}-${{ github.run_id }}
          path: |
            dist/
            stats.html
          if-no-files-found: error
    timeout-minutes: 5
  deploy:
    name: Deploy
    permissions:
      actions: read # required in private repositories
      contents: read
      deployments: write
      pull-requests: write
    needs:
      - build
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ needs.build.outputs.environment }}
    secrets: inherit
