name: Build

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
    outputs:
      build-artifact-name:
        description: The name of the build artifact
        value: ${{ jobs.build.outputs.build-artifact-name }}

env:
  PACKAGE: ${{ inputs.package }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-artifact-name: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
        timeout-minutes: 1

      - run: |
          if [[ -z $PACKAGE ]]; then
            pnpm install
          else
            pnpm install --filter="$PACKAGE"
          fi
        env:
          PACKAGE: ${{ inputs.package }}

      - run: |
          if [[ -z $PACKAGE ]]; then
            pnpm run build
          else
            pnpm run build --filter="$PACKAGE"
          fi
        env:
          PACKAGE: ${{ inputs.package }}

      - id: set-build-artifact-name
        name: Set build artifact name
        run: echo "build-artifact-name=build-artifact-run-$GITHUB_RUN_ID-$PACKAGE" >> "$GITHUB_OUTPUT"
        env:
          PACKAGE: ${{ inputs.package }}

      - name: Tar build artifact
        run: tar cvf "$BUILD_ARTIFACT_NAME".tar "$PACKAGE"/dist/
        env:
          PACKAGE: ${{ inputs.package }}
          BUILD_ARTIFACT_NAME: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}
          path: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}.tar
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: stats-artifact-run-${{ github.run_id }}
          path: stats.html
          if-no-files-found: error
    timeout-minutes: 5
