name: Build

on:
  workflow_call:
    inputs:
      node-modules-cache-path:
        required: true
        type: string
      node-modules-cache-key:
        required: true
        type: string
    outputs:
      build-artifact-name:
        description: The name of the build artifact
        value: ${{ jobs.build.outputs.build-artifact-name }}
      build-artifact-download-path:
        description: The path to the directory where the build artifact should be downloaded
        value: ${{ jobs.build.outputs.build-artifact-download-path }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-artifact-name: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}
      build-artifact-download-path: ${{ steps.set-build-artifact-download-path.outputs.build-artifact-download-path }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
        timeout-minutes: 1

      - id: cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.node-modules-cache-path }}
          key: ${{ inputs.node-modules-cache-key }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: npm run build

      - id: set-build-artifact-name
        name: Set build artifact name
        run: echo "build-artifact-name=build-artifact-run-$GITHUB_RUN_ID" >> "$GITHUB_OUTPUT"

      - id: set-build-artifact-download-path
        name: Set build artifact path
        run: echo "build-artifact-download-path=dist/" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-build-artifact-name.outputs.build-artifact-name }}
          path: ${{ steps.set-build-artifact-download-path.outputs.build-artifact-download-path }}
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: stats-artifact-run-${{ github.run_id }}
          path: stats.html
          if-no-files-found: error
    timeout-minutes: 5
