name: Caller Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Caller-Job1:
  Caller-Job1:
  Caller-Job1:
  Call:
    needs: [Caller-Job1, Caller-Job2, Caller-Job3]
    strategy:
      matrix:
        input1:
          - value 1
          - value 2
          - value 3
      fail-fast: true
    uses: ./.github/workflows/called.yaml
    with:
      input1: ${{ matrix.input1 }}
