name: Called

on:
  workflow_call:
    inputs:
      input1:
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$INPUT1"
        env:
          INPUT1: ${{ inputs.input1 }}
