name: Caller Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  caller-job1:
    uses: ./.github/workflows/called.yaml
    with:
      input1: value of input1
