name: Called Workflow

on:
  workflow_call:

jobs:
  called-job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy"
    strategy:
      matrix:
        environment:
          - staging
          - production
