name: Caller

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: caller > job1 > step1
  job2:
    needs:
      - job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/called.yaml
        with:
          input1: value of input1
