name: Called Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string

jobs:
  called-job1:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Output `environment` value
        run: echo environment is "$environment"
        env:
          environment: ${{ inputs.environment }}
    strategy:
      matrix:
        environment: ${{ inputs.environment }}
