name: CI/CD (Admin)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force-deploy:
        default: false
        description: 'Force deployment'
        type: boolean

env:
  FORCE_DEPLOY: ${{ github.event.inputs.force-deploy }}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  ci-cd:
    name: CI/CD
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    uses: ./.github/workflows/ci-cd.yaml
    with:
      project: admin
      source-paths: |
        apps/admin/functions/**
        apps/admin/public/**
        apps/admin/src/**
        apps/admin/astro.config.ts
        apps/admin/package.json
        apps/admin/pnpm-lock.yaml
        apps/admin/tsconfig.json
      build-artifacts-path: |
        apps/admin/dist/
        apps/admin/stats.html
      force-deploy: ${{ inputs.force-deploy }}
    secrets: inherit
