name: CI/CD (admin)

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     force-deploy:
  #       description: Force deploy
  #       type: boolean

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  prepare:
    name: Prepare
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.prepare.outputs.environment }}
      needs-deploy: ${{ steps.prepare.outputs.needs-deploy }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          filter: tree:0
          fetch-depth: 0

      - id: prepare
        uses: ./.github/actions/prepare
        with:
          project: admin
    timeout-minutes: 5

  check:
    name: Check
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - uses: ./.github/actions/check
    timeout-minutes: 5

  build:
    name: Build
    needs:
      - prepare
      - check
    runs-on: ubuntu-latest
    outputs:
      build-artifact-name: ${{ steps.build.outputs.build-artifact-name }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - id: build
        uses: ./.github/actions/build
        with:
          project: admin
          build-artifact-content-path: |
            apps/admin/dist/
            apps/admin/stats.html
    timeout-minutes: 5

  deploy:
    name: Deploy
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    needs:
      - prepare
      - build
    # if: inputs.force-deploy || needs.prepare.outputs.needs-deploy == 'true'
    if: needs.prepare.outputs.needs-deploy == 'true'
    runs-on: ubuntu-latest
    environment: ${{ needs.prepare.outputs.environment }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - uses: ./.github/actions/deploy
        with:
          app: admin
          build-artifact-name: ${{ needs.build.outputs.build-artifact-name }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ needs.prepare.outputs.environment }}
          working-directory: apps/admin/
    timeout-minutes: 5
