name: CI/CD (Web)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force-deploy:
        description: 'Force deployment'
        type: boolean

env:
  FORCE_DEPLOY: ${{ github.event.inputs.force-deploy }}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  ci-cd:
    name: CI/CD
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    uses: ./.github/workflows/ci-cd.yaml
    with:
      project: web
      source-paths: |
        apps/web/functions/**
        apps/web/public/**
        apps/web/src/**
        apps/web/astro.config.ts
        apps/web/package.json
        apps/web/pnpm-lock.yaml
        apps/web/tsconfig.json
      build-artifacts-path: |
        apps/web/dist/
        apps/web/stats.html
      force-deploy: ${{ inputs.force-deploy }}
    secrets: inherit
