name: CI/CD (Web)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force-deploy:
        description: 'Force deployment'
        type: boolean

env:
  PROJECT: web
  FORCE_DEPLOY: ${{ inputs.force-deploy }}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  prepare:
    name: Prepare
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.prepare.outputs.environment }}
      source-files-changed: ${{ steps.prepare.outputs.source-files-changed }}
    steps:
      - uses: actions/checkout@v4

      - id: prepare
        uses: ./.github/actions/prepare
        with:
          project: web
    timeout-minutes: 5

  check:
    name: Check
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/check.yaml
    timeout-minutes: 5

  build:
    name: Build
    needs:
      - prepare
      - check
    uses: ./.github/workflows/build.yaml
    with:
      project: web
      build-artifacts-path: |
        apps/web/dist/
        apps/web/stats.html
    secrets: inherit

  deploy:
    name: Deploy
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    needs:
      - prepare
      - build
    if: inputs.force-deploy || needs.prepare.outputs.source-files-changed == 'true'
    uses: ./.github/workflows/deploy.yaml
    with:
      project: web
      build-artifacts-name: ${{ needs.build.outputs.build-artifacts-name }}
      public-path: apps/web/dist/
      environment: ${{ needs.prepare.outputs.environment }}
    secrets: inherit
