name: Check

on:
  workflow_call:
    inputs:
      node-modules-cache-path:
        required: true
        type: string
      node-modules-cache-key:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
        timeout-minutes: 1

      - id: cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.node-modules-cache-path }}
          key: ${{ inputs.node-modules-cache-key }}

      - if: steps.cache.outputs.cache-hit == false
        run: npm ci

      - run: npm run check
    timeout-minutes: 5
