name: Check

on:
  workflow_call:
    inputs:
      pnpm-store-cache-path:
        required: true
        type: string
      pnpm-store-cache-key:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - uses: actions/cache@v4
        with:
          path: ${{ inputs.pnpm-store-cache-path }}
          key: ${{ inputs.pnpm-store-cache-key }}

      - run: pnpm install

      - run: pnpm run check
    timeout-minutes: 5
