name: CI/CD

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  building:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          path: |
            dist/
            stats.html
          if-no-files-found: error
  deployment:
    name: Deployment
    needs:
      - building
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - run: echo "[DEBUG] env.environment is ${{ env.environment }}"
      - run: echo "[DEBUG] '$ENVIRONMENT' is $ENVIRONMENT"
      - uses: actions/download-artifact@v4
      - id: deploy
        run: |
          echo "Deploying $(ls -al artifact/)"
          echo "deployment-url=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"
        env:
          DEPLOYMENT_URL: ${{ env.environment == 'production' && 'https://example.com' || 'https://preview.example.com' }}
      - run: |
          echo "$COMMAND_OUTPUT"
          echo "$DEPLOYMENT_URL"
        env:
          COMMAND_OUTPUT: ${{ steps.deploy.outputs.command-output }}
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
