name: CI/CD

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      environment: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
  deployment:
    name: Deployment
    needs:
      - build
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
