name: CI/CD

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      source-paths:
        required: true
        type: string
      build-artifacts-path:
        required: true
        type: string
      force-deploy:
        required: true
        type: boolean

env:
  PROJECT: ${{ inputs.project }}
  SOURCE_PATHS: ${{ inputs.source-paths }}
  BUILD_ARTIFACTS_PATH: ${{ inputs.build-artifacts-path }}
  FORCE_DEPLOY: ${{ inputs.force-deploy }}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Prepare
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/prepare.yaml
    with:
      project: ${{ inputs.project }}
      source-paths: ${{ inputs.source-paths }}
    secrets: inherit

  check:
    name: Check
    needs:
      - prepare
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  build:
    name: Build
    needs:
      - prepare
      - check
    uses: ./.github/workflows/build.yaml
    with:
      project: ${{ inputs.project }}
      build-artifacts-path: ${{ inputs.build-artifacts-path }}
    secrets: inherit

  deploy:
    name: Deploy
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    needs:
      - prepare
      - build
    if: ${{ ! startsWith(inputs.project, '@workspace/') && (inputs.force-deploy || needs.prepare.outputs.source-files-changed) }}
    uses: ./.github/workflows/deploy.yaml
    with:
      project: ${{ inputs.project }}
      build-artifacts-name: ${{ needs.build.outputs.build-artifacts-name }}
      public-path: apps/${{ inputs.project }}/dist/
      environment: ${{ needs.prepare.outputs.environment }}
    secrets: inherit
