name: CI/CD

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  building:
    name: Building
    uses: ./.github/workflows/building.yaml
    with:
      environment: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
  deployment:
    name: Deployment
    needs:
      - building
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
