name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force-deploy:
        description: 'Force deployment'
        type: boolean

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  prepare:
    name: Prepare
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/prepare.yaml
    with:
      force-deploy: ${{ inputs.force-deploy }}
    secrets: inherit

  check:
    name: Check
    needs:
      - prepare
    uses: ./.github/workflows/check.yaml
    with:
      node-modules-cache-path: ${{ needs.prepare.outputs.node-modules-cache-path }}
      node-modules-cache-key: ${{ needs.prepare.outputs.node-modules-cache-key }}
    secrets: inherit

  build:
    name: Build
    needs:
      - prepare
      - check
    uses: ./.github/workflows/build.yaml
    with:
      node-modules-cache-path: ${{ needs.prepare.outputs.node-modules-cache-path }}
      node-modules-cache-key: ${{ needs.prepare.outputs.node-modules-cache-key }}
    secrets: inherit

  deploy:
    name: Deploy
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    needs:
      - prepare
      - build
    if: inputs.force-deploy || needs.prepare.outputs.build-changed == 'true' || needs.prepare.outputs.workflows-changed == 'true'
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      build-artifact-name: ${{ needs.build.outputs.build-artifact-name }}
      build-artifact-download-path: ${{ needs.build.outputs.build-artifact-download-path }}
    secrets: inherit
