name: CI/CD

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
  deploy:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: production
