name: CI/CD

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force-deploy:
        default: false
        description: 'Force Deploy workflow to run'
        type: boolean

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
      node-modules-cache-path: '**/node_modules/'
      node-modules-cache-key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      src-changed: ${{ steps.filter.outputs.src }}
      workflows-changed: ${{ steps.filter.outputs.workflows }}
    steps:
      - run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_CHANGES_BASE_REF: $GITHUB_EVENT_CHANGES_BASE_REF"
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"
        env:
          GITHUB_EVENT_CHANGES_BASE_REF: ${{ github.event.changes.base.ref }}
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - uses: actions/checkout@v4

      - id: filter
        if: inputs.force-deploy == false
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - functions/**
              - public/**
              - astro.config.js
              - src/**
              - package-lock.json
              - package.json
              - tsconfig.json
            workflows:
              - .github/workflows/deploy.yaml

  build:
    name: Build
    permissions:
      contents: read
      pull-requests: read # required by dorny/paths-filter
    needs:
      - prepare
    uses: ./.github/workflows/build.yaml
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      node-modules-cache-path: ${{ needs.prepare.outputs.node-modules-cache-path }}
      node-modules-cache-key: ${{ needs.prepare.outputs.node-modules-cache-key }}
    secrets: inherit

  deploy:
    name: Deploy
    permissions:
      actions: read # required in private repositories by unlike-ltd/github-actions-cloudflare-pages
      contents: read
      deployments: write # required by unlike-ltd/github-actions-cloudflare-pages
      pull-requests: write # required by unlike-ltd/github-actions-cloudflare-pages
    needs:
      - prepare
      - build
    if: inputs.force-deploy || needs.prepare.outputs.src-changed == 'true' || needs.prepare.outputs.workflows-changed == 'true'
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      node-modules-cache-path: ${{ needs.prepare.outputs.node-modules-cache-path }}
      node-modules-cache-key: ${{ needs.prepare.outputs.node-modules-cache-key }}
      build-artifact-name: ${{ needs.build.outputs.build-artifact-name }}
      build-artifact-download-dir: ${{ needs.build.outputs.build-artifact-download-dir }}
    secrets: inherit
