name: CI/CD

defaults:
  run:
    shell: bash

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
  deploy-to-production:
    name: Deploy
    needs:
      - build
    if: github.event_name == 'push'
    uses: ./.github/workflows/deployment.yaml
