name: CI/CD

defaults:
  run:
    shell: bash

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build.yaml
  cd:
    name: CD
    needs:
      - ci
    if: github.event_name == 'push'
    uses: ./.github/workflows/deployment.yaml
