name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force-deploy:
        description: 'Force deployment'
        type: boolean

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  prepare:
    name: Prepare
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/prepare.yaml
    secrets: inherit

  check:
    name: Check
    needs:
      - prepare
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  build:
    name: Build apps
    needs:
      - prepare
      - check
    if: needs.prepare.outputs.changed-apps != '[]'
    strategy:
      matrix:
        project: ${{ fromJSON(needs.prepare.outputs.changed-apps) }}
    uses: ./.github/workflows/build.yaml
    with:
      project: ${{ matrix.project }}
      build-artifacts-path: |
        apps/${{ matrix.project }}/dist/
        apps/${{ matrix.project }}/stats.html
    secrets: inherit

  deploy:
    name: Deploy
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    needs:
      - prepare
      - build
    if: inputs.force-deploy || needs.prepare.outputs.changed-apps != '[]'
    strategy:
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.changed-apps) }}
    uses: ./.github/workflows/deploy.yaml
    with:
      app: ${{ matrix.app }}
      build-artifacts-name: ${{ needs.build.outputs.build-artifacts-name }}
      public-path: apps/${{ matrix.app }}/dist/
      environment: ${{ needs.prepare.outputs.environment }}
    secrets: inherit
