name: Delete deployments

on:
  pull_request:
    branches:
      - main
    types:
      - closed

defaults:
  run:
    shell: bash

jobs:
  delete-deployments:
    name: Delete deployments
    permissions:
      actions: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Check if required variables are defined
        run: |
          echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"

      - if: ${{ github.ref_name != 'main' }}
        uses: unlike-ltd/github-actions-cloudflare-pages/delete@729e3e59a4977be918c8d7e2ff08ec4e1532d0d6 # v2.3.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
