name: Delete deployments

on:
  pull_request:
    branches:
      - main
    types:
      - closed

defaults:
  run:
    shell: bash

jobs:
  delete-deployments:
    name: Delete deployments
    permissions:
      actions: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Check if required variables are defined
        run: |
          echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"

      - if: ${{ github.ref_name != 'main' }}
        uses: unlike-ltd/github-actions-cloudflare-pages/delete@5428201f91a158bbf876391773769e720c80dabb # v2.4.1
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
