name: Delete deployments

on:
  pull_request:
    branches:
      - main
    types:
      - closed

defaults:
  run:
    shell: bash

jobs:
  delete-deployments:
    name: Delete deployments
    permissions:
      actions: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Check if required variables are defined
        run: |
          echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"

      - if: ${{ github.ref_name != 'main' }}
        uses: unlike-ltd/github-actions-cloudflare-pages/delete@889f6ada1a0961747e66430120f40ec46a97254c # v2.4.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
