name: Deployment

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/download-artifact@v4
      - run: ls -al artifact/
      - id: deploy
        run: echo "deployment-url=https://example.com" >> "$GITHUB_OUTPUT"
