name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - run: 'echo "environment: $ENVIRONMENT"'
      - uses: actions/download-artifact@v4
      - id: deploy
        run: |
          echo "Deploying $(ls -al artifact/)"
          echo "deployment-url=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"
        env:
          DEPLOYMENT_URL: ${{ inputs.environment == 'production' && 'https://example.com' || 'https://preview.example.com' }}
