name: Deployment

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: ls -al artifact/
      - run: echo "$MY_VAR"
        env:
          MY_VAR: ${{ vars.MY_VAR }}
