name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_call:
    inputs:
      build-artifact-name:
        required: true
        type: string
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
    steps:
      - name: Check if required variables are defined
        run: |
          echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"
          echo "CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID:?configuration variable is not defined}"
          echo "CLOUDFLARE_PROJECT_NAME: ${CLOUDFLARE_PROJECT_NAME:?configuration variable is not defined}"

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
        timeout-minutes: 1

      - run: pnpm install

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build-artifact-name }}

      - name: Untar build artifact
        run: tar xvf ${{ inputs.build-artifact-name }}.tar

      - uses: unlike-ltd/github-actions-cloudflare-pages@8c09c46bd39321b4aa3784852491d9e4f09e1566 # v1.2.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ inputs.environment }}
    timeout-minutes: 5

  delete-deployments:
    name: Delete deployments
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
    steps:
      - name: Check if required variables are defined
        run: |
          echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"
          echo "CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID:?configuration variable is not defined}"
          echo "CLOUDFLARE_PROJECT_NAME: ${CLOUDFLARE_PROJECT_NAME:?configuration variable is not defined}"

      - uses: unlike-ltd/github-actions-cloudflare-pages@8c09c46bd39321b4aa3784852491d9e4f09e1566 # v1.2.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ inputs.environment }}
    timeout-minutes: 5
