name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  download-artifact:
    name: Download Artifact
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - run: |
          echo DEBUG
          echo "inputs.environment: $ENVIRONMENT"
      - uses: actions/download-artifact@v4
  deploy:
    name: Deploy
    needs:
      - download-artifact
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.wrangler.outputs.deployment-url }}
    steps:
      - id: wrangler
        run: |
          echo "Deploying $(ls -al artifact/)"
          echo "deployment-url=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"
        env:
          DEPLOYMENT_URL: ${{ inputs.environment == 'production' && 'https://example.com' || 'https://preview.example.com' }}
