name: Deployment

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: ls -Rla
      - uses: actions/checkout@v4
      - run: ls -Rla
      - uses: actions/download-artifact@v4
      - run: ls -Rla
