name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  deployment:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: ls -al artifact/
      - id: deploy
        run: echo "deployment-url=https://example.com" >> "$GITHUB_OUTPUT"
