name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      build-artifact-name:
        required: true
        type: string
      build-artifact-download-path:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: ${{ github.event_name == 'pull_request' && 'Delete deployments' || 'Deploy' }}
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
    steps:
      - name: Check if required variables are defined
        run: |
          echo "CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?secret is not defined}"
          echo "CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID:?configuration variable is not defined}"
          echo "CLOUDFLARE_PROJECT_NAME: ${CLOUDFLARE_PROJECT_NAME:?configuration variable is not defined}"

      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ inputs.build-artifact-download-path }}

      - uses: unlike-ltd/github-actions-cloudflare-pages@8c09c46bd39321b4aa3784852491d9e4f09e1566 # v1.2.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: ${{ inputs.build-artifact-download-path || 'directory' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ inputs.environment || 'preview' }}
    timeout-minutes: 5
