name: Prepare

on:
  workflow_call:
    outputs:
      environment:
        description: The environment to deploy to
        value: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
      build-changed:
        description: Whether the build has changed
        value: ${{ jobs.prepare.outputs.build-changed }}
      workflows-changed:
        description: Whether the workflows have changed
        value: ${{ jobs.prepare.outputs.workflows-changed }}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Prepare
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      build-changed: ${{ steps.filter.outputs.build }}
      workflows-changed: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            build:
              - functions/**
              - public/**
              - src/**
              - astro.config.js
              - package.json
              - pnpm-lock.yaml
              - tsconfig.json
            workflows:
              - .github/workflows/deploy.yaml
    timeout-minutes: 5
