name: Prepare

on:
  workflow_call:
    outputs:
      environment:
        description: The environment to deploy to
        value: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
      changed-apps:
        description: An array containing names of changed apps
        value: ${{ jobs.prepare.outputs.changed-apps }}

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-apps: ${{ steps.filter-apps.outputs.changes }}
    steps:
      - uses: actions/checkout@v4

      - id: filter-apps
        uses: dorny/paths-filter@v3
        with:
          filters: |
            admin:
              - apps/admin/functions/**
              - apps/admin/public/**
              - apps/admin/src/**
              - apps/admin/astro.config.ts
              - apps/admin/package.json
              - apps/admin/pnpm-lock.yaml
              - apps/admin/tsconfig.json
            web:
              - apps/web/functions/**
              - apps/web/public/**
              - apps/web/src/**
              - apps/web/astro.config.ts
              - apps/web/package.json
              - apps/web/pnpm-lock.yaml
              - apps/web/tsconfig.json
    timeout-minutes: 5
