name: Prepare

on:
  workflow_call:
    inputs:
      source-paths:
        required: true
        type: string
    outputs:
      environment:
        description: The environment to deploy to
        value: ${{ github.ref_name == github.event.repository.default_branch && 'production' || 'preview' }}
      source-files-changed:
        description: Whether the source files have changed
        value: ${{ jobs.prepare.outputs.source-files-changed }}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Prepare
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      source-files-changed: ${{ steps.filter.outputs.source }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            source: ${{ inputs.source-paths }}
    timeout-minutes: 5
